version: "2"
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="akuchars"
      - MONGODB_PASS="haslo123"
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017