# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: circleci/rabbitmq
      - image: circleci/mongo:latest
      - image: circleci/postgres:latest

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGODB_USER: "akuchars"
      MONGODB_PASS: "haslo123"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - mvn install -DskipTests
            - v1-dependencies-

      - run: mvn compile install dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test